"""Render annotated screenshots of the app's real UI for the user guide.

Images in a guide rot faster than the prose does: a renamed field or a moved
section leaves a picture that confidently shows the wrong thing. So these are
GENERATED from the same widgets the application builds -- the actual
SimulationControlsPanel, the actual HelpDialog -- and regenerated by re-running
this script, rather than cropped by hand from a window that existed once.

    python tools/make_tutorial_screenshots.py
    python tools/make_tutorial_screenshots.py --out docs/user_guide/images

Every shot is annotated here too: numbered callouts and highlight boxes are drawn
against the widget's own geometry, so a callout cannot drift off the control it
points at the way a hand-placed arrow does.

WHAT THIS CANNOT DO
-------------------
The 3D octree view is VTK, which needs a real OpenGL context. Offscreen on
Windows that fails with "failed to get valid pixel format", so the viewer is not
captured here. Run with --with-viewer on a machine with a display to include it;
without it the guide uses the renders already in docs/surf_report/.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys

# Must precede any Qt import: the platform plugin is chosen at QApplication
# construction and cannot be switched afterwards.
if "--with-viewer" not in sys.argv:
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PySide6 import QtCore, QtGui, QtWidgets  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from graph_visualizer.simulation_controls_panel import (  # noqa: E402
    MODE_HEADLESS,
    MODE_LIVE,
    SimulationControlsPanel,
)

ACCENT = QtGui.QColor("#e85d04")
CALLOUT_BG = QtGui.QColor("#e85d04")
CALLOUT_FG = QtGui.QColor("#ffffff")
PANEL_WIDTH = 430


class _Qt:
    """The binding shim the panel expects."""

    QtCore = QtCore
    QtWidgets = QtWidgets


#: Tried in order; the first that loads becomes the UI font.
_FONT_CANDIDATES = (
    (r"C:\Windows\Fonts\segoeui.ttf", r"C:\Windows\Fonts\segoeuib.ttf"),
    (r"C:\Windows\Fonts\arial.ttf", r"C:\Windows\Fonts\arialbd.ttf"),
    ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
     "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
)


def install_fonts() -> str:
    """Give the offscreen platform a font, or every glyph renders as a box.

    QT_QPA_PLATFORM=offscreen ships NO font database at all -- QFontDatabase
    reports zero families -- so the first run of this script produced twelve
    perfectly laid out screenshots in which every character was tofu. The fonts
    have to be registered explicitly from disk.
    """
    for regular, bold in _FONT_CANDIDATES:
        if not Path(regular).is_file():
            continue
        font_id = QtGui.QFontDatabase.addApplicationFont(regular)
        if font_id < 0:
            continue
        families = QtGui.QFontDatabase.applicationFontFamilies(font_id)
        if Path(bold).is_file():
            QtGui.QFontDatabase.addApplicationFont(bold)
        if families:
            QtWidgets.QApplication.setFont(QtGui.QFont(families[0], 9))
            return families[0]
    return ""


def build_panel(mode: str) -> tuple[SimulationControlsPanel, QtWidgets.QWidget]:
    panel = SimulationControlsPanel(_Qt, mode=mode)
    host = QtWidgets.QWidget()
    host.setStyleSheet("QWidget { background: #ffffff; font-size: 12px; }")
    form = QtWidgets.QFormLayout(host)
    panel.build(form)
    panel.build_readout_editor()
    panel._apply_mode()
    host.setFixedWidth(PANEL_WIDTH)
    host.adjustSize()
    host.show()
    QtWidgets.QApplication.processEvents()
    return panel, host


def _section_widget(panel: SimulationControlsPanel, key: str) -> QtWidgets.QWidget | None:
    return panel._sections.get(key)


def grab(widget: QtWidgets.QWidget, scale: int = 2) -> QtGui.QPixmap:
    """Grab at ``scale`` device pixels per logical pixel, so text stays crisp when
    the guide is printed or zoomed."""
    widget.setAttribute(QtCore.Qt.WA_OpaquePaintEvent, False)
    pixmap = QtGui.QPixmap(widget.size() * scale)
    pixmap.setDevicePixelRatio(scale)
    pixmap.fill(QtGui.QColor("#ffffff"))
    widget.render(pixmap, QtCore.QPoint(), QtGui.QRegion(), QtWidgets.QWidget.DrawChildren)
    return pixmap


def annotate(
    pixmap: QtGui.QPixmap,
    boxes: list[tuple[QtCore.QRect, str]],
    scale: int = 2,
    margin_left: int = 46,
) -> QtGui.QPixmap:
    """Draw a numbered callout and a highlight box per entry.

    ``boxes`` is [(rect in the grabbed widget's coordinates, caption)]. The canvas
    is widened on the left so the numbers sit outside the UI rather than on top of
    it -- a callout covering the control it names is worse than none.
    """
    width = pixmap.width() + margin_left * scale
    canvas = QtGui.QPixmap(width, pixmap.height())
    canvas.setDevicePixelRatio(scale)
    canvas.fill(QtGui.QColor("#ffffff"))

    painter = QtGui.QPainter(canvas)
    painter.setRenderHint(QtGui.QPainter.Antialiasing, True)
    painter.drawPixmap(QtCore.QPointF(margin_left, 0), pixmap)

    font = painter.font()
    font.setBold(True)
    font.setPointSizeF(9.5)
    painter.setFont(font)

    for number, (rect, _caption) in enumerate(boxes, start=1):
        shifted = QtCore.QRect(
            rect.x() + margin_left - 3, rect.y() - 3, rect.width() + 6, rect.height() + 6
        )
        pen = QtGui.QPen(ACCENT)
        pen.setWidthF(1.8)
        painter.setPen(pen)
        painter.setBrush(QtCore.Qt.NoBrush)
        painter.drawRoundedRect(shifted, 4, 4)

        centre = QtCore.QPointF(margin_left / 2.0, shifted.center().y())
        radius = 11.0
        painter.setBrush(CALLOUT_BG)
        painter.setPen(QtGui.QPen(CALLOUT_BG))
        painter.drawEllipse(centre, radius, radius)
        painter.setPen(QtGui.QPen(CALLOUT_FG))
        painter.drawText(
            QtCore.QRectF(centre.x() - radius, centre.y() - radius, radius * 2, radius * 2),
            QtCore.Qt.AlignCenter,
            str(number),
        )
        # A leader from the number, stopping at the edge of the screenshot. Drawing
        # it all the way to the highlight box runs it straight through the row's
        # label, which reads as the label being struck out.
        painter.setPen(QtGui.QPen(ACCENT, 1.2))
        painter.drawLine(
            QtCore.QPointF(centre.x() + radius, centre.y()),
            QtCore.QPointF(margin_left - 2, centre.y()),
        )
    painter.end()
    return canvas


def rect_of(child: QtWidgets.QWidget, root: QtWidgets.QWidget) -> QtCore.QRect:
    """``child``'s rectangle in ``root``'s coordinate system."""
    top_left = child.mapTo(root, QtCore.QPoint(0, 0))
    return QtCore.QRect(top_left, child.size())


def save(pixmap: QtGui.QPixmap, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    pixmap.save(str(path), "PNG")
    return path


def shoot_section(
    panel: SimulationControlsPanel,
    host: QtWidgets.QWidget,
    section_key: str,
    row_keys: list[str],
    out: Path,
    scale: int = 2,
) -> Path | None:
    """One section of the panel, with a callout on each named row."""
    section = _section_widget(panel, section_key)
    if section is None:
        print(f"  ! no section {section_key!r}")
        return None
    section.adjustSize()
    QtWidgets.QApplication.processEvents()
    pixmap = grab(section, scale)
    boxes = []
    for key in row_keys:
        entry = panel._rows.get(key)
        if entry is None:
            print(f"  ! no row {key!r} in {section_key!r}")
            continue
        widget = entry[1]
        if not widget.isVisibleTo(section):
            print(f"  ! row {key!r} is hidden in this mode")
            continue
        boxes.append((rect_of(widget, section), key))
    annotated = annotate(pixmap, boxes, scale)
    return save(annotated, out)


def shoot_help_dialog(out: Path, scale: int = 2) -> Path | None:
    """The help search, with a real query typed into it and real results."""
    from graph_visualizer.help_center import HelpCenter

    live_panel, live_host = build_panel(MODE_LIVE)
    headless_panel, headless_host = build_panel(MODE_HEADLESS)

    class _Tabs:
        titles = [
            "3D Octree Graph Editor",
            "2D Network Graph",
            "Heat Transfer Simulation",
            "Thermal Validation",
            "Headless Run",
        ]

        def count(self):
            return len(self.titles)

        def tabText(self, index):  # noqa: N802
            return self.titles[index]

        def setCurrentIndex(self, index):  # noqa: N802
            pass

    class _Owner:
        def __init__(self, panel):
            self.panel = panel

    class _App:
        QtCore = QtCore
        QtWidgets = QtWidgets
        window = None
        view_tabs = _Tabs()

        def __init__(self):
            self.simulation_tab = _Owner(live_panel)
            self.headless_run_tab = _Owner(headless_panel)

    center = HelpCenter(_App())
    dialog = center.show_dialog(focus_search=True)
    dialog.search_box.setText("heater power")
    QtWidgets.QApplication.processEvents()
    dialog.widget.resize(760, 470)
    QtWidgets.QApplication.processEvents()

    pixmap = grab(dialog.widget, scale)
    boxes = [
        (rect_of(dialog.search_box, dialog.widget), "search"),
        (rect_of(dialog.results, dialog.widget), "results"),
    ]
    saved = save(annotate(pixmap, boxes, scale), out)
    live_host.close()
    headless_host.close()
    return saved


def shoot_tutorials_dialog(out: Path, scale: int = 2) -> Path | None:
    from graph_visualizer.help_center import HelpCenter

    live_panel, live_host = build_panel(MODE_LIVE)

    class _Tabs:
        titles = ["Heat Transfer Simulation"]

        def count(self):
            return 1

        def tabText(self, index):  # noqa: N802
            return self.titles[0]

        def setCurrentIndex(self, index):  # noqa: N802
            pass

    class _Owner:
        panel = live_panel

    class _App:
        QtCore = QtCore
        QtWidgets = QtWidgets
        window = None
        view_tabs = _Tabs()
        simulation_tab = _Owner()

    center = HelpCenter(_App())
    dialog = center.show_dialog(tutorial_key="controller")
    dialog.widget.resize(760, 470)
    QtWidgets.QApplication.processEvents()
    pixmap = grab(dialog.widget, scale)
    saved = save(annotate(pixmap, [], scale, margin_left=8), out)
    live_host.close()
    return saved


#: (filename, mode, section key, rows to call out). The rows are checked against
#: the live panel at run time, so a renamed row prints a warning here instead of
#: silently producing a picture with a callout on the wrong control.
SHOTS: list[tuple[str, str, str, list[str]]] = [
    ("run_section.png", MODE_LIVE, "run",
     ["input_mode", "controller", "mimo_pi_kp", "mimo_pi_ki"]),
    ("controller_limits.png", MODE_LIVE, "controller_limits",
     ["mimo_default_heater_max_power_W", "mimo_heater_slew_rate_W_per_s",
      "mimo_undershoot_weight"]),
    ("controller_design.png", MODE_LIVE, "modal_design",
     ["modal_operating_temperature", "modal_order", "modal_build", "export_controller"]),
    ("sys_id.png", MODE_LIVE, "sys_id", ["run_sys_id"]),
    ("environment.png", MODE_LIVE, "environment", []),
    ("properties.png", MODE_LIVE, "properties", []),
    ("cryocooler.png", MODE_LIVE, "cryocooler", []),
    ("mimo_qp.png", MODE_LIVE, "mimo",
     ["mimo_lambda_u", "mimo_rho_du", "mimo_integral_abs_max"]),
    ("headless_run_section.png", MODE_HEADLESS, "run",
     ["snapshot_interval_s", "checkpoint_interval_s"]),
    ("headless_solver.png", MODE_HEADLESS, "solver", ["implicit_method"]),
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="docs/user_guide/images")
    parser.add_argument("--scale", type=int, default=2, help="device pixels per logical pixel")
    parser.add_argument(
        "--with-viewer",
        action="store_true",
        help="use a real display so the VTK 3D view can be captured too",
    )
    args = parser.parse_args()

    out_dir = Path(args.out)
    app = QtWidgets.QApplication.instance() or QtWidgets.QApplication([])
    _ = app
    family = install_fonts()
    if not family:
        print(
            "error: no usable font was found, and the offscreen platform has none of "
            "its own -- every glyph would render as an empty box.",
            file=sys.stderr,
        )
        return 1
    print(f"font: {family}")

    written: list[Path] = []
    panels: dict[str, tuple[SimulationControlsPanel, QtWidgets.QWidget]] = {}
    for filename, mode, section_key, rows in SHOTS:
        if mode not in panels:
            panels[mode] = build_panel(mode)
        panel, host = panels[mode]
        print(f"{filename} ({mode} / {section_key})")
        path = shoot_section(panel, host, section_key, rows, out_dir / filename, args.scale)
        if path is not None:
            written.append(path)

    print("help_search.png")
    path = shoot_help_dialog(out_dir / "help_search.png", args.scale)
    if path is not None:
        written.append(path)
    print("help_tutorials.png")
    path = shoot_tutorials_dialog(out_dir / "help_tutorials.png", args.scale)
    if path is not None:
        written.append(path)

    print(f"\nWrote {len(written)} image(s) to {out_dir}:")
    for path in written:
        print(f"  {path.name:28} {path.stat().st_size // 1024:5} KB")
    if not args.with_viewer:
        print(
            "\nThe 3D octree view is not included: VTK needs a real OpenGL context. "
            "Re-run with --with-viewer on a machine with a display to add it."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
